#!/bin/bash

# =====================================================================
# Script to design protein binder sequences using ProteinMPNN
# =====================================================================
#
# This script processes PDB files containing protein complexes with:
# - A binder chain (usually chain A) with backbone generated by RFdiffusion
#   The binder chain has a sequence of all Gly, except for conserved motif residues
# - A target chain (usually chain B) that should remain fixed/unchanged
#
# The script will:
# 1. Identify which positions in the binder chain are not glycine (conserved motif)
# 2. Run ProteinMPNN to design new sequences for the binder chain while keeping
#    the conserved motif residues and target chain fixed
# 3. Output designed sequences for each input PDB
#
# Usage:
#   ./design_binders.sh -i <input_folder> -o <output_folder> [-b <binder_chain_id>] [-t <target_chain_id>] [-n <num_sequences>] [-T <temperature>] [-p <path_to_pMPNN>]
#
# Required arguments:
#   -i, --input_folder    Folder containing input PDB files
#   -o, --output_folder   Folder to save output files
#   -p, --path_to_pMPNN   Path to ProteinMPNN directory
#
# Optional arguments:
#   -b, --binder_chain    Chain ID of the binder (default: A)
#   -t, --target_chain    Chain ID of the target protein (default: B)
#   -n, --num_seqs        Number of sequences to generate per target (default: 2)
#   -T, --temperature     Sampling temperature (default: 0.1)
#   -h, --help            Show this help message
# =====================================================================

# Activate ProteinMPNN environment
source /home/esteban/anaconda3/etc/profile.d/conda.sh
conda activate pMPNN

# Default values
INPUT_FOLDER=""
OUTPUT_FOLDER=""
PATH_TO_pMPNN="/home/esteban/ProteinMPNN"
BINDER_CHAIN="B"
TARGET_CHAIN="A"
NUM_SEQUENCES=1
TEMPERATURE="0.0001"
BATCH_SIZE=1
AAs_TO_OMIT='C'

# Function to display help
show_help() {
    echo "Usage: $(basename "$0") -i <input_folder> -o <output_folder> [-p <path_to_pMPNN>] [-b <binder_chain_id>] [-t <target_chain_id>] [-n <num_sequences>] [-T <temperature>]"
    echo ""
    echo "Design protein binder sequences using ProteinMPNN"
    echo ""
    echo "Required arguments:"
    echo "  -i, --input_folder    Folder containing input PDB files"
    echo "  -o, --output_folder   Folder to save output files"
    echo ""
    echo "Optional arguments:"
    echo "  -p, --path_to_pMPNN   Path to ProteinMPNN directory (default: $PATH_TO_pMPNN)"
    echo "  -b, --binder_chain    Chain ID of the binder (default: $BINDER_CHAIN)"
    echo "  -t, --target_chain    Chain ID of the target protein (default: $TARGET_CHAIN)"
    echo "  -n, --num_seqs        Number of sequences to generate per target (default: $NUM_SEQUENCES)"
    echo "  -T, --temperature     Sampling temperature (default: $TEMPERATURE)"
    echo "  -h, --help            Show this help message"
    exit 1
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -i|--input_folder)
            INPUT_FOLDER="$2"
            shift
            shift
            ;;
        -o|--output_folder)
            OUTPUT_FOLDER="$2"
            shift
            shift
            ;;
        -p|--path_to_pMPNN)
            PATH_TO_pMPNN="$2"
            shift
            shift
            ;;
        -b|--binder_chain)
            BINDER_CHAIN="$2"
            shift
            shift
            ;;
        -t|--target_chain)
            TARGET_CHAIN="$2"
            shift
            shift
            ;;
        -n|--num_seqs)
            NUM_SEQUENCES="$2"
            shift
            shift
            ;;
        -T|--temperature)
            TEMPERATURE="$2"
            shift
            shift
            ;;
        -h|--help)
            show_help
            ;;
        *)
            echo "Error: Unknown option $1"
            show_help
            ;;
    esac
done

# Check if required arguments are provided
if [ -z "$INPUT_FOLDER" ] || [ -z "$OUTPUT_FOLDER" ]; then
    echo "Error: Input folder and output folder are required."
    show_help
fi

# Check if input folder exists
if [ ! -d "$INPUT_FOLDER" ]; then
    echo "Error: Input folder '$INPUT_FOLDER' does not exist."
    exit 1
fi

# Create output folder if it doesn't exist
if [ ! -d "$OUTPUT_FOLDER" ]; then
    mkdir -p "$OUTPUT_FOLDER"
    echo "Created output directory: $OUTPUT_FOLDER"
fi

echo "===== Protein Binder Design with ProteinMPNN ====="
echo "Input folder:        $INPUT_FOLDER"
echo "Output folder:       $OUTPUT_FOLDER"
echo "ProteinMPNN path:    $PATH_TO_pMPNN"
echo "Binder chain:        $BINDER_CHAIN"
echo "Target chain:        $TARGET_CHAIN"
echo "Num sequences:       $NUM_SEQUENCES"
echo "Temperature:         $TEMPERATURE"
echo "=============================================="

# Process each input PDB file in a folder-based approach that works with the helper scripts

# Step 1: Create a temporary working directory for each PDB
for pdb_file in "$INPUT_FOLDER"/*.pdb; do
    if [ ! -f "$pdb_file" ]; then
        echo "No PDB files found in $INPUT_FOLDER"
        exit 1
    fi
    
    base_name=$(basename "$pdb_file" .pdb)
    temp_pdb_dir="$OUTPUT_FOLDER/temp_${base_name}"
    mkdir -p "$temp_pdb_dir"
    
    # Copy the PDB to its own temporary directory
    cp "$pdb_file" "$temp_pdb_dir/"
    
    echo "Prepared $base_name for processing"
done

# Step 2: Process all PDBs one by one
for pdb_file in "$INPUT_FOLDER"/*.pdb; do
    base_name=$(basename "$pdb_file" .pdb)
    echo "Processing: $base_name"
    
    # Set up paths
    temp_pdb_dir="$OUTPUT_FOLDER/temp_${base_name}"
    final_output_dir="$OUTPUT_FOLDER/${base_name}"
    mkdir -p "$final_output_dir"
    
    # Paths for intermediate files
    path_for_parsed_chains="$final_output_dir/parsed_pdbs.jsonl"
    path_for_assigned_chains="$final_output_dir/assigned_pdbs.jsonl"
    path_for_fixed_positions="$final_output_dir/fixed_pdbs.jsonl"
    
    # Parse the PDB file (helper script expects a folder of PDBs)
    echo "  Parsing PDB structure..."
    python "${PATH_TO_pMPNN}/helper_scripts/parse_multiple_chains.py" \
        --input_path="$temp_pdb_dir" \
        --output_path="$path_for_parsed_chains"
    
    # Extract conserved motif positions (non-GLY residues in binder chain)
    echo "  Identifying conserved motif positions..."
    fixed_positions=$(python - "$pdb_file" "$BINDER_CHAIN" <<EOF
import sys
import os
from Bio.PDB import PDBParser

pdb_file = sys.argv[1]
binder_chain = sys.argv[2]

# Parse PDB file
parser = PDBParser(QUIET=True)
structure = parser.get_structure("protein", pdb_file)

# Get residue positions that are not glycine in the binder chain
fixed_pos = []
for model in structure:
    for chain in model:
        if chain.id == binder_chain:
            pos = 1  # We'll use sequential numbering starting from 1
            for residue in chain:
                if residue.get_resname() != "GLY":
                    fixed_pos.append(str(pos))
                pos += 1

# Return the result as a space-separated string
print(" ".join(fixed_pos))
EOF
)
    
    echo "  Conserved motif positions in $BINDER_CHAIN: $fixed_positions"
    
    # Assign chains to design (binder) and fix (target)
    echo "  Assigning chains to design/fix..."
    python "${PATH_TO_pMPNN}/helper_scripts/assign_fixed_chains.py" \
        --input_path="$path_for_parsed_chains" \
        --output_path="$path_for_assigned_chains" \
        --chain_list "$BINDER_CHAIN"
    
    # Set fixed positions in the binder chain (the conserved motif)
    echo "  Setting fixed positions..."
    python "${PATH_TO_pMPNN}/helper_scripts/make_fixed_positions_dict.py" \
        --input_path="$path_for_parsed_chains" \
        --output_path="$path_for_fixed_positions" \
        --chain_list "$BINDER_CHAIN" \
        --position_list "$fixed_positions"
    
    # Run ProteinMPNN to design sequences
    echo "  Running ProteinMPNN for sequence design..."
    python "${PATH_TO_pMPNN}/protein_mpnn_run.py" \
        --jsonl_path "$path_for_parsed_chains" \
        --chain_id_jsonl "$path_for_assigned_chains" \
        --fixed_positions_jsonl "$path_for_fixed_positions" \
        --out_folder "$final_output_dir" \
        --num_seq_per_target "$NUM_SEQUENCES" \
        --sampling_temp "$TEMPERATURE" \
        --omit_AAs "$AAs_TO_OMIT" \
        --batch_size "$BATCH_SIZE"
    
    echo "  Done with $base_name"
    echo ""
done

# Clean up temporary directories
echo "Cleaning up temporary files..."
for pdb_file in "$INPUT_FOLDER"/*.pdb; do
    base_name=$(basename "$pdb_file" .pdb)
    temp_pdb_dir="$OUTPUT_FOLDER/temp_${base_name}"
    rm -rf "$temp_pdb_dir"
done

echo "All PDBs processed successfully!"
echo "Results are saved in: $OUTPUT_FOLDER"
