#!/bin/bash

# =====================================================================
# Script to design protein binder sequences using ProteinMPNN
# =====================================================================
#
# This script processes PDB files containing protein complexes with:
# - A target that may be a monomer or a dimer (chains fixed/unchanged)
# - A single binder backbone (chain C by default) generated by RFdiffusion
#   The binder chain has a sequence of all Gly, except for conserved motif residues
#
# The script will:
# 1. Identify which positions in the binder chain are not glycine (conserved motif)
# 2. Run ProteinMPNN to design new sequences for the binder chain while keeping
#    the conserved motif residues and all target chains fixed
# 3. Output designed sequences for each input PDB
#
# Usage:
#   ./design_binders.sh -i <input_folder> -o <output_folder> [-b <binder_chain_id>] [-t <target_chain_ids>] [-n <num_sequences>] [-T <temperature>] [-p <path_to_pMPNN>]
#
# Required arguments:
#   -i, --input_folder    Folder containing input PDB files
#   -o, --output_folder   Folder to save output files
#   -p, --path_to_pMPNN   Path to ProteinMPNN directory
#
# Optional arguments:
#   -b, --binder_chain    Chain ID of the binder (default: C)
#   -t, --target_chains   Chain ID(s) of the target protein(s), space-separated (default: "A B")
#                         For a monomer use e.g. -t "A"; for a dimer use e.g. -t "A B"
#                         NOTE: any chain not listed as the binder is automatically fixed by
#                         ProteinMPNN, so this argument is currently only used for display purposes.
#   -n, --num_seqs        Number of sequences to generate per target (default: 2)
#   -T, --temperature     Sampling temperature (default: 0.1)
#   -h, --help            Show this help message
# =====================================================================

# Activate ProteinMPNN environment
source /home/esteban/anaconda3/etc/profile.d/conda.sh
conda activate pMPNN

# Default values
INPUT_FOLDER=""
OUTPUT_FOLDER=""
PATH_TO_pMPNN="/home/esteban/ProteinMPNN"
BINDER_CHAIN="C"        # CHANGED: was "B", now "C" for the binder
TARGET_CHAINS="A B"     # CHANGED: was single chain "A", now supports dimer "A B"
NUM_SEQUENCES=1
TEMPERATURE="0.0001"
BATCH_SIZE=1
AAs_TO_OMIT='C'

# Function to display help
show_help() {
    echo "Usage: $(basename "$0") -i <input_folder> -o <output_folder> [-p <path_to_pMPNN>] [-b <binder_chain_id>] [-t <target_chain_ids>] [-n <num_sequences>] [-T <temperature>]"
    echo ""
    echo "Design protein binder sequences using ProteinMPNN"
    echo ""
    echo "Required arguments:"
    echo "  -i, --input_folder    Folder containing input PDB files"
    echo "  -o, --output_folder   Folder to save output files"
    echo ""
    echo "Optional arguments:"
    echo "  -p, --path_to_pMPNN   Path to ProteinMPNN directory (default: /home/esteban/ProteinMPNN)"
    echo "  -b, --binder_chain    Chain ID of the binder to design (default: C)"
    echo "  -t, --target_chains   Chain ID(s) of the fixed target, space-separated (default: \"A B\")"
    echo "                        Example: -t \"A\" for monomer, -t \"A B\" for dimer"
    echo "  -n, --num_seqs        Number of sequences to generate per target (default: 2)"
    echo "  -T, --temperature     Sampling temperature (default: 0.0001)"
    echo "  -h, --help            Show this help message"
    exit 1
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -i|--input_folder)
            INPUT_FOLDER="$2"
            shift
            shift
            ;;
        -o|--output_folder)
            OUTPUT_FOLDER="$2"
            shift
            shift
            ;;
        -p|--path_to_pMPNN)
            PATH_TO_pMPNN="$2"
            shift
            shift
            ;;
        -b|--binder_chain)
            BINDER_CHAIN="$2"
            shift
            shift
            ;;
        -t|--target_chains)    # CHANGED: renamed from --target_chain to --target_chains
            TARGET_CHAINS="$2"
            shift
            shift
            ;;
        -n|--num_seqs)
            NUM_SEQUENCES="$2"
            shift
            shift
            ;;
        -T|--temperature)
            TEMPERATURE="$2"
            shift
            shift
            ;;
        -h|--help)
            show_help
            ;;
        *)
            echo "Error: Unknown option $1"
            show_help
            ;;
    esac
done

# Check if required arguments are provided
if [ -z "$INPUT_FOLDER" ] || [ -z "$OUTPUT_FOLDER" ]; then
    echo "Error: Input folder and output folder are required."
    show_help
fi

# Check if input folder exists
if [ ! -d "$INPUT_FOLDER" ]; then
    echo "Error: Input folder '$INPUT_FOLDER' does not exist."
    exit 1
fi

# Create output folder if it doesn't exist
if [ ! -d "$OUTPUT_FOLDER" ]; then
    mkdir -p "$OUTPUT_FOLDER"
    echo "Created output directory: $OUTPUT_FOLDER"
fi

echo "===== Protein Binder Design with ProteinMPNN ====="
echo "Input folder:        $INPUT_FOLDER"
echo "Output folder:       $OUTPUT_FOLDER"
echo "ProteinMPNN path:    $PATH_TO_pMPNN"
echo "Binder chain:        $BINDER_CHAIN  (will be redesigned)"
echo "Target chain(s):     $TARGET_CHAINS  (will be held fixed)"
echo "Num sequences:       $NUM_SEQUENCES"
echo "Temperature:         $TEMPERATURE"
echo "=============================================="

# Step 1: Create a temporary working directory for each PDB
for pdb_file in "$INPUT_FOLDER"/*.pdb; do
    if [ ! -f "$pdb_file" ]; then
        echo "No PDB files found in $INPUT_FOLDER"
        exit 1
    fi

    base_name=$(basename "$pdb_file" .pdb)
    temp_pdb_dir="$OUTPUT_FOLDER/temp_${base_name}"
    mkdir -p "$temp_pdb_dir"

    # Copy the PDB to its own temporary directory
    cp "$pdb_file" "$temp_pdb_dir/"

    echo "Prepared $base_name for processing"
done

# Step 2: Process all PDBs one by one
for pdb_file in "$INPUT_FOLDER"/*.pdb; do
    base_name=$(basename "$pdb_file" .pdb)
    echo "Processing: $base_name"

    # Set up paths
    temp_pdb_dir="$OUTPUT_FOLDER/temp_${base_name}"
    final_output_dir="$OUTPUT_FOLDER/${base_name}"
    mkdir -p "$final_output_dir"

    # Paths for intermediate files
    path_for_parsed_chains="$final_output_dir/parsed_pdbs.jsonl"
    path_for_assigned_chains="$final_output_dir/assigned_pdbs.jsonl"
    path_for_fixed_positions="$final_output_dir/fixed_pdbs.jsonl"

    # Parse the PDB file (helper script expects a folder of PDBs)
    echo "  Parsing PDB structure..."
    python "${PATH_TO_pMPNN}/helper_scripts/parse_multiple_chains.py" \
        --input_path="$temp_pdb_dir" \
        --output_path="$path_for_parsed_chains"

    # Extract conserved motif positions (non-GLY residues in binder chain)
    # CHANGED: now searches the binder chain (C) rather than the old binder chain (B)
    echo "  Identifying conserved motif positions in binder chain $BINDER_CHAIN..."
    fixed_positions=$(python - "$pdb_file" "$BINDER_CHAIN" <<EOF
import sys
from Bio.PDB import PDBParser

pdb_file = sys.argv[1]
binder_chain = sys.argv[2]

parser = PDBParser(QUIET=True)
structure = parser.get_structure("protein", pdb_file)

fixed_pos = []
for model in structure:
    for chain in model:
        if chain.id == binder_chain:
            pos = 1
            for residue in chain:
                if residue.get_resname() != "GLY":
                    fixed_pos.append(str(pos))
                pos += 1

print(" ".join(fixed_pos))
EOF
)

    echo "  Conserved motif positions in chain $BINDER_CHAIN: $fixed_positions"

    # Assign the binder chain for design; all other chains (A, B, ...) are automatically fixed.
    # CHANGED: --chain_list now explicitly specifies only the binder (C); ProteinMPNN
    # treats every chain absent from this list as fixed, so chains A and B are both held constant.
    echo "  Assigning chain $BINDER_CHAIN for design (chains $TARGET_CHAINS will be fixed)..."
    python "${PATH_TO_pMPNN}/helper_scripts/assign_fixed_chains.py" \
        --input_path="$path_for_parsed_chains" \
        --output_path="$path_for_assigned_chains" \
        --chain_list "$BINDER_CHAIN"

    # Set fixed positions within the binder chain (the conserved motif residues)
    echo "  Setting fixed motif positions within chain $BINDER_CHAIN..."
    python "${PATH_TO_pMPNN}/helper_scripts/make_fixed_positions_dict.py" \
        --input_path="$path_for_parsed_chains" \
        --output_path="$path_for_fixed_positions" \
        --chain_list "$BINDER_CHAIN" \
        --position_list "$fixed_positions"

    # Run ProteinMPNN to design sequences
    echo "  Running ProteinMPNN for sequence design..."
    python "${PATH_TO_pMPNN}/protein_mpnn_run.py" \
        --jsonl_path "$path_for_parsed_chains" \
        --chain_id_jsonl "$path_for_assigned_chains" \
        --fixed_positions_jsonl "$path_for_fixed_positions" \
        --out_folder "$final_output_dir" \
        --num_seq_per_target "$NUM_SEQUENCES" \
        --sampling_temp "$TEMPERATURE" \
        --omit_AAs "$AAs_TO_OMIT" \
        --batch_size "$BATCH_SIZE"

    echo "  Done with $base_name"
    echo ""
done

# Clean up temporary directories
echo "Cleaning up temporary files..."
for pdb_file in "$INPUT_FOLDER"/*.pdb; do
    base_name=$(basename "$pdb_file" .pdb)
    temp_pdb_dir="$OUTPUT_FOLDER/temp_${base_name}"
    rm -rf "$temp_pdb_dir"
done

echo "All PDBs processed successfully!"
echo "Results are saved in: $OUTPUT_FOLDER"
